const guide = [
  [
    "Compensation Philosophy",
    "Large yearly cash bonuses, raises, and stock refreshers (target is 20+% of TC)",
    "Yearly cash bonuses, raises, or stock refreshers (target is 10 - 20% of TC)",
    "Either yearly cash bonuses, raises, or stock refreshers (target 0 - 10% of TC)",
    "Raises matching or around the rate of inflation (2.0%)",
    "No raises"
  ],
  [
    "Vacation & Time Off",
    "Unlimited",
    "15 - 21 days",
    "10 - 14 days",
    "0 - 9 days",
    "None"
  ],
  [
    "PTO & Sick Days",
    "Unlimited or 12+",
    "9 - 11 days",
    "8 days",
    "4 - 7 days",
    "0 - 3 days",
  ],
  [
    "Meals & Food",
    "Free breakfast, lunch & dinner (3/3 meals)",
    "2 of free breakfast, lunch or dinner (2/3 meals)",
    "1 of free breakfast, lunch or dinner (1/3 meals)",
    "No free food but subsidized meals",
    "No free food",
  ],
  [
    "Snacks",
    "Fully stocked snack area (extensive quantity and quality of all varieties of snacks)",
    "Mostly stocked snack area (most common brands of snacks, usually unhealthy snacks, some healthy snacks)",
    "Consistent snack stock (usually org-managed ie. leadership-organized)",
    "Inconsistent snack stock (usually team-managed ie. manager-organzied)",
    "No snacks",
  ],
  [
    "Coffee & Drinks",
    "Extensive variety of drinks, fridges fully stocked, gourmet drink machines like multi-purpose cafe machines, smoothie machines etc.",
    "Large variety of drinks (soda, coffee, juice, beer, etc.), possibly some custom drink machines",
    "Some drinks (coffee, milk, soda, juice, beer, etc.)",
    "A limited variety or inconsistent stock of drinks (coffee, milk, soda, tea)",
    "Only coffee, tea bags, or nothing",
  ],
  [
    "401k Matching",
    "25+% match",
    "15 - 24%",
    "5 - 14%",
    "1 - 4% (the median match is 3% in America but it's much higher in the tech industry)",
    "0%",
  ],
  [
    "Health & Fitness",
    "Credits or reimbursements for health & wellness expenses ($500+/yr), onsite facilities, or free memberships",
    "Credits or reimbursements for health & wellness expenses ($500+/yr)",
    "Credits or reimbursements for health & wellness expenses ($100 - $499/yr)",
    "Discounts or tax benefits for health & wellness (0 - $100/yr)",
    "None",
  ],
  [
    "Mental Health & Therapy",
    "Unlimited access in excess of insurance",
    "Large number of session covered in excess of insurance",
    "Covered under insurance",
    "Discounted or subsidized under insurance",
    "None",
  ],
  [
    "Green Card Sponsorship",
    "Will sponsor immediately",
    "Will sponsor after 0 - 3 months",
    "Will sponsor after 4 - 6 months",
    "Will sponsor after 6+ months",
    "Will not sponsor",
  ],
  [
    "Company Holidays",
    "12 holidays (all holidays + week-long shutdowns)",
    "10 - 12 holidays (all holidays & some floating days after holidays)",
    "9 holidays (all federal holidays & most optional holidays)",
    "7 - 8 holidays (all federal holidays & some optional holidays)",
    "6 holidays (just federal holidays)",
  ],
  [
    "Cellphone Allowance",
    "$65+/month",
    "$50 - $64/month",
    "$31 - $49/month",
    "$1 - $30/month",
    "None",
  ],
  [
    "Charity Donation Match",
    "$5000+/yr",
    "$2500 to $4999/yr",
    "$1000 to $2499/yr",
    "0 to $999/yr",
    "None",
  ],
  [
    "Commuter Benefits",
    "Company shuttle, unlimited passes or full subsidy of public transport, ridesharing $250+/month, free parking",
    "Company shuttle, Mostly subsidized public transport, ridesharing, or parking",
    "Company shuttle, Discounted or partially subsidized public transport, ridesharing, or parking",
    "Limited subsidies or limited number of tokens for public transport or ridesharing, no free parking",
    "None",
  ],
  [
    "Maternity & paternity leave",
    "Leave 4+ months paid leave, no restrictions, additional cash bonus",
    "4+ months paid leave",
    "3 months paid leave",
    "2 months paid leave",
    "1 month paid leave or none",
  ],
  [
    "Childcare",
    "Cash & subsidies for in-home or out of home child care ($2000+ value/yr)",
    "Subsidies for in-home or out of home child care ($1000+/yr)",
    "Subsidies for in-home or out of home child care (up to $1000/yr)",
    "Discount for in-home or out of home child care (up to $500/yr)",
    "None",
  ],
  [
    "Surrogacy, in vitro fertilization, adoption assistance",
    "Extensive coverage of adoption and/or surrogacy and/or IVF, significant subsidies ($20000+)",
    "Great coverage of adoption and/or surrogacy and/or IVF ($10000+)",
    "Some coverage of adoption and/or surrogacy and/or IVF (~$5000)",
    "Limited coverage or coverage on 1 of adoption, surrogacy or IVF (~$2000)",
    "None",
  ],
  [
    "Onsite Facilities",
    "Extensive, modern facilities covering multiple chores or healthcare needs. Doctors on call, health care centers, massage facilities etc.",
    "Facilities covering some healthcare or personal needs. Facilities are high quality but not top notch",
    "Facilities are just for work. Buildings are modern and in respectable neighbourhoods",
    "Buildings are old, medium sized, in off neighbourhoods, no ammenities",
    "Buildings are run down, small, crowded, in dangerous neighbourhoods, no ammenities",
  ],
  [
    "Recreation",
    "All office sports and more activities (ping pong tables, foosball tables, video games)",
    "Most office sports or activities, still widely available",
    "Some office sports or activities depends on location",
    "Very few office sports or activities (i.e. 1 foosball table) or depends on org/team",
    "None",
  ],
  [
    "Tuition",
    "$10000+ benefit/yr",
    "$5000 - $9999/yr",
    "$1000 - $4999/yr",
    "$1 - $999/yr",
    "None",
  ],
  [
    "Health Insurance (basic)",
    "Free basic coverage & low deductible",
    "Free basic coverage",
    "Paid basic coverage & low deductible",
    "Paid basic coverage & high deductible",
    "None",
  ],
  [
    "Company contributions to HSA (Health Savings Account)",
    "Company provides contributions ($1000+)",
    "Company provides contributions ($750+)",
    "Company provides contributions ($500+)",
    "Company provides contributions ($250+)",
    "None",
  ],
  [
    "Miscellaneous",
    "Large monetary or personal benefit",
    "Some monetary or personal benefit",
    "Monetary or personal benefit with some restrictions",
    "Monetary or personal benefit with restrictions, is uncommon, forced, or not transferrable",
    "None",
  ]
];

export default guide;
